namespace: argocd

helmDefaults:
  createNamespace: true

repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argocd
    chart: argo/argo-cd
    values:
      - argocd/values.yaml